### ISSUE TITLE
Feature Request: Add a seperate 'Contact Us' Page with Form Validation.

### ISSUE THREAD

**Issue by aritroo** [AyushMann29/EatNFun#13]
Hello @AyushMann29 
I want to Implement a 'Contact Us' page with a responsive design, featuring a form for user inquiries. Integrate form validation to ensure correct data input, improving user interaction and ensuring seamless communication. This will enhance user experience and reliability. Please assign me under hacktoberfest. 
Thank You.

**Comment by AyushMann29** [comment]
Assigned @aritroo
