### ISSUE TITLE
Spelling mistake in README file

### ISSUE THREAD

**Issue by varyan03** [AyushMann29/EatNFun#15]
Hello @AyushMann29, I found a minor spelling mistake in the README file. The word "Aesthetics" is misspelled as "Astheatics". It should be corrected to "Aesthetics". I would be happy to fix this issue and submit a pull request if you could kindly assign it to me under Hacktoberfest. Thanks!

**Comment by AyushMann29** [comment]
If you are looking for no-code hacktoberfest label, you can beautify the readme file instead of just fixing spelling. I will assign it to you if you work on beautifying readme.md

**Comment by AyushMann29** [comment]
assigned @varyan03 for beautify of README.md
