### ISSUE TITLE
Nav bar enhance and Drop Down error

### ISSUE THREAD

**Issue by manisha069** [AyushMann29/EatNFun#21]
![{D1C1BF2B-C14F-4427-8F7E-5FBC3345F2E1}](https://github.com/user-attachments/assets/e9584b20-c00f-4857-94f4-122289ab0782)
![{F82D82DC-080D-49BA-8205-00541E2BF3DA}](https://github.com/user-attachments/assets/5ff01358-c4b5-4964-b7b2-4fd7554bc7f9)

Currently the Nav bar is pretty crooked with too much spacing due to which the last drop down value go out of page, also there is not enough space in the drop down due to which values are coming up clumped.

I'd like to work on this to correct this issue, please assign this to me.

**Comment by AyushMann29** [comment]
Assigned @manisha069
