### ISSUE TITLE
Fixing the Position of Dark Mode/Light Mode Button

### ISSUE THREAD

**Issue by harshit69x** [AyushMann29/EatNFun#22]
![image](https://github.com/user-attachments/assets/c54534f5-4576-45d7-8c6e-3c21894f0f38)
 
### Fixing the issue
Fix the position of the Dark Mode/Light Mode toggle button to ensure it remains consistently placed across all pages and screen sizes. This will improve usability, ensuring that users can easily locate the button regardless of where they are on the page. The button could be fixed to the top-right corner, allowing quick access even during scrolling. This will enhance the overall user experience, especially on long pages or mobile devices.

@AyushMann29 please assign me this issue.

**Comment by BarryByte** [comment]
@AyushMann29 If this issue is not assigned to anyone , can you please assign this issue to me. Thanks.
