### ISSUE TITLE
[BUG]: Repetitive dropdown present in navigation bar. 

### ISSUE THREAD

**Issue by aritroo** [AyushMann29/EatNFun#29]
Hi @AyushMann29 ,
The "Contact Us" dropdown menu in the navigation bar contains repetitive entries. The options for "Manager," "Co-Manager," and "Reception" are displayed twice. I can fix it, please assign me .

**Comment by AyushMann29** [comment]
Can you add a screenshot also? Thanks

**Comment by aritroo** [comment]
Sure 

<img width="1470" alt="Screenshot 2024-10-04 at 9 49 00 PM" src="https://github.com/user-attachments/assets/ea845c40-dc82-460d-b0f5-a32991116a72">

**Comment by AyushMann29** [comment]
Fix this @aritroo under hacktoberfest
