### ISSUE TITLE
PopUp Text not visible clearly

### ISSUE THREAD

**Issue by KUMUD-TECH** [AyushMann29/EatNFun#31]
Popup text of Contact, events and about is not visible clearly.

![Screenshot 2024-10-04 130906](https://github.com/user-attachments/assets/cfdeb3f0-09a8-4072-9f89-ff797ea03bc8)
![Screenshot 2024-10-04 130916](https://github.com/user-attachments/assets/3e6f4ee3-2031-4b56-a574-b76efa6acfa7)
![Screenshot 2024-10-04 130850](https://github.com/user-attachments/assets/0a798512-679c-4d8d-8825-fb6af99825dc)

**Comment by KUMUD-TECH** [comment]
Assign this issue to me. 
I want to work on this issue and make it correct.

Add hacktoberfest label .
Thank you

**Comment by AyushMann29** [comment]
Assigned @KUMUD-TECH

**Comment by harshitkumargupta** [comment]
Hi @AyushMann29 ,
Can you please assign this to me under Hacktoberfest Tag.
