### ISSUE TITLE
Addition of Favicon

### ISSUE THREAD

**Issue by harshit69x** [AyushMann29/EatNFun#34]
![image](https://github.com/user-attachments/assets/2cb201c6-cf05-43e6-a244-13d3edc8293a)
 
### addition of favicon on the page

@AyushMann29 Please assign me this issue

**Comment by rahulholkar16** [comment]
Hey I want to add a favicon icon in this web page. pls assine me.

**Comment by rahulholkar16** [comment]
Please check and review #36 PR.

**Comment by harshit69x** [comment]
Whats the use, there are no labels yet
