### ISSUE TITLE
Add Events Calendar Component Matching the Current Design

### ISSUE THREAD

**Issue by Mefisto04** [AyushMann29/EatNFun#35]
**Description:**
I would like to contribute by adding an **Events Calendar** component to the project. This feature will allow users to view upcoming events in a visually organized manner, and it will align with the existing design language of the web application. The calendar will be responsive and user-friendly, enhancing the overall user experience by providing a seamless way to track and view important events.

**Proposed Contribution:**
- Create a responsive Events Calendar component that matches the current design aesthetics.
- Ensure the component can display event details such as date, time, and event description.
- Integrate the calendar component smoothly with the existing architecture.
- Provide customizable options for future event additions and updates.

**Additional Information:**
- Please assign this issue to me so that I can begin working on it.
- Also add the tag of **Hacktoberfest**.

**Comment by AyushMann29** [comment]
Assigned @Mefisto04
