### ISSUE TITLE
Cafeteria Menu Cards are not looking good

### ISSUE THREAD

**Issue by danishsheikh1122** [AyushMann29/EatNFun#38]
I can change the Cafeteria Menu cards to look more styled and more user friendly.
I can change the card and make it coverable and on hover the card will rotate and all the description of the menu its prize will shown.It will look more cooler then before 
<img width="1393" alt="Screenshot 2024-10-05 at 10 21 38 PM" src="https://github.com/user-attachments/assets/a424c166-3427-4f3a-bddb-cb0437cba45c">

**Comment by AyushMann29** [comment]
Also they are not shown in firefox, if you can see it too. Assigned @danishsheikh1122

**Comment by Stranger1298** [comment]
Hey I can make the menu card looks more attractive please assign this issue to me

**Comment by Stranger1298** [comment]
And if you have certain design to make it then please share it

**Comment by danishsheikh1122** [comment]
but sir certainly i didnt have firefox browser
