### ISSUE TITLE
Responsiveness of the page

### ISSUE THREAD

**Issue by Jils31** [AyushMann29/EatNFun#52]
The website is not responsive , thus not portable for the mobile devices.

I can solve this issue , please assign this issue to me!

[Screencast from 2024-10-10 02-16-25.webm](https://github.com/user-attachments/assets/bde62edc-8d22-4fe2-88e7-eb9da13a2e57)

**Comment by AyushMann29** [comment]
Assigned @Jils31

**Comment by Jils31** [comment]
Yes I'm working on it!, I'll update you when I'm done with the issue

**Comment by ParvamShah1** [comment]
Please solve the issue fast brother .
