### ISSUE TITLE
Social Media Links in Footer Not Connected

### ISSUE THREAD

**Issue by sambhavbohra** [AyushMann29/EatNFun#53]
Social Media Links in Footer Not Connected

### Problem:
The social media icons in the footer currently link to `#` instead of actual social media accounts. This creates a broken user experience.

### Proposed Solution:
1. Connect the social media icons to the relevant social media platforms. If social handles are not available, redirect them to the login pages of each social media platform as a fallback.

### Steps:
- Facebook: Link to Facebook login or personal profile
- Twitter: Link to Twitter login or personal profile
- Instagram: Link to Instagram login or personal profile
- LinkedIn: Link to LinkedIn login or personal profile

##Screenshot
![Screenshot 2024-10-10 024218](https://github.com/user-attachments/assets/1deb8bc9-6cda-4330-bb34-7104aaaa484f)

**Comment by sambhavbohra** [comment]
@AyushMann29 Hey please can you assisgn me this issue under HACKTOBER !!

**Comment by AyushMann29** [comment]
assigned @sambhavbohra
