### ISSUE TITLE
Overlapping Text on Main Homepage

### ISSUE THREAD

**Issue by sambhavbohra** [AyushMann29/EatNFun#54]
Overlapping Text on Main Homepage

### Problem:
Text elements on the main homepage are overlapping, which negatively impacts the readability and user experience.

### Proposed Solution:
1. Review the CSS layout to identify the cause of the overlap.
2. Apply CSS fixes to ensure proper spacing, alignment, and responsiveness across different screen sizes.

##Screenshot 
![Screenshot 2024-10-10 030203](https://github.com/user-attachments/assets/a23a168f-103d-4e87-9dfc-9036b9ae2abc)

**Comment by sambhavbohra** [comment]
@AyushMann29 Please assign this issue

**Comment by AyushMann29** [comment]
try to fix it and attatch screenshot with it @sambhavbohra

**Comment by sambhavbohra** [comment]
@Crimson-Typhoon-147 I have already worked on this issue and fixed it !! 
@AyushMann29 Please check the PR and merge it !!
