### ISSUE TITLE
Change the old twitter logo to new logo 

### ISSUE THREAD

**Issue by hemangtk** [AyushMann29/EatNFun#61]
I noticed that the twitter logo your site is using is the old and out dated one 
i would like to update it to the new logo 
![image](https://github.com/user-attachments/assets/a1272a73-6651-4331-957f-09d786b0ad8c)

**Comment by AyushMann29** [comment]
Assigned @hemangtk

**Comment by hemangtk** [comment]
Heyy @AyushMann29 i have searched the html ,css ,js codes but im not able to find where have to added the images from,
could you please give me light on that so i can fix it right away?
Thank you!!

**Comment by hemangtk** [comment]
heyy @AyushMann29 raised a pr for the same 
please let me know if there are any changes required
