### ISSUE TITLE
Bug :  Cafeteria menu cards alignment issue

### ISSUE THREAD

**Issue by sumana2004** [AyushMann29/EatNFun#67]
Hello @AyushMann29 ,  the text within the cafeteria menu cards is not properly aligned. This issue needs to be resolved to ensure alignment of the text across all menu cards for a clean look. Please assign me under hacktoberfest.
I have attached the screenshot for reference.

![EatNFun](https://github.com/user-attachments/assets/6d70f280-bb1a-40f1-a27f-f6d807b2243e)

**Comment by AyushMann29** [comment]
Assigned @sumana2004
